version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2
    environment:
    - discovery.type=single-node
    ports:
      - 9200:9200
  pagnol:
    build: ./packaging/docker
