apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pagnol.fullname" . }}
  labels:
    {{- include "pagnol.labels" . | nindent 4 }}
data:
  spec.yaml: |
    ---
    {{- toYaml .Values.config.actions | default "{}" | nindent 4 }}
