apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pagnol.fullname" . }}
  labels:
    {{- include "pagnol.labels" . | nindent 4 }}
  {{- if .Values.hook.enabled }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    helm.sh/hook: {{ .Values.hook.type }}
    helm.sh/hook-delete-policy: {{ .Values.hook.delete_policy }}
  {{- end }}
spec:
  {{- with .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- with .Values.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ . }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "pagnol.labels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{ toYaml . | indent 8 }}
        {{- end }}
      {{- with .Values.pod.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
      - name: pagnol
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
        - "--actions"
        - "/opt/spec.yaml"
        - "--url"
        - {{ .Values.config.url }}
        {{- if .Values.config.debug }}
        - "--debug"
        {{- end }}
        {{- if .Values.config.ignoreError }}
        - "--ignore-error"
        {{- end }}
        securityContext:
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
        {{- with .Values.pod.extraEnvs }}
        env: {{ toYaml . | nindent 10 }}
        {{- end }}
        resources: {{ toYaml .Values.pod.resources | nindent 10 }}
        volumeMounts:
        - name: spec
          mountPath: "/opt"
          readOnly: true
      volumes:
      - name: spec
        configMap:
          name: {{ include "pagnol.fullname" . }}
          items:
          - key: "spec.yaml"
            path: "spec.yaml"
